framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        default_bus: command.bus

        buses:
            command.bus: ~
            query.bus: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: 'in-memory://'
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'App\Wallet\Application\Command\CreateWalletCommand': sync
